apiVersion: v1
kind: Service
metadata:
  name: myservice
  namespace: default
spec:
  selector:
    app: myservice
  type: ClusterIP
  ports:
  - name: myservice
    protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30001
---
